//
// Generated file, do not edit! Created by opp_msgtool 6.2 from Item.msg.
//

#ifndef __ITEM_M_H
#define __ITEM_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Item;
/**
 * Class generated from <tt>Item.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Item
 * {
 *     int counter = 0;
 *     bool isDiscarded = false; //Is item discarded?
 *     double generationTime = -1.0; //Time at which item is generated
 *     double arrivalTime = -1.0; //Time at which item arrives at factory (is stored in input array)
 *     double startTime = -1.0; //Time at which first production stage starts
 *     double productionTime = -1.0; //Time at which item is finished (last production stage ends)
 * }
 * </pre>
 */
class Item : public ::omnetpp::cPacket
{
  protected:
    int counter = 0;
    bool isDiscarded_ = false;
    double generationTime = -1.0;
    double arrivalTime = -1.0;
    double startTime = -1.0;
    double productionTime = -1.0;

  private:
    void copy(const Item& other);

  protected:
    bool operator==(const Item&) = delete;

  public:
    Item(const char *name=nullptr, short kind=0);
    Item(const Item& other);
    virtual ~Item();
    Item& operator=(const Item& other);
    virtual Item *dup() const override {return new Item(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getCounter() const;
    virtual void setCounter(int counter);
    virtual void increaseCounter();

    virtual bool isDiscarded() const;
    virtual void setIsDiscarded(bool isDiscarded);

    virtual double getGenerationTime() const;
    virtual void setGenerationTime(double generationTime);

    virtual double getArrivalTime() const;
    virtual void setArrivalTime(double arrivalTime);

    virtual double getStartTime() const;
    virtual void setStartTime(double startTime);

    virtual double getProductionTime() const;
    virtual void setProductionTime(double productionTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Item& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Item& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Item *fromAnyPtr(any_ptr ptr) { return check_and_cast<Item*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ITEM_M_H

